## We'll continue this importing the module of numpy which is very useful for the mathametical operations like in this case it is the matrix multiplication

In [37]:
import numpy as np


In [38]:
a=[1,2,3,4]
type(a)

list

In [39]:
arr=np.array(a)
type(arr)

numpy.ndarray

In [40]:
b=np.array([1,2,3,4])
a+b

array([2, 4, 6, 8])

In [41]:
mul=a*b
mul

array([ 1,  4,  9, 16])

In [42]:
sub=a-b
sub

array([0, 0, 0, 0])

In [43]:
div=a/b
div

array([1., 1., 1., 1.])

In [44]:
mod=a%b
mod

array([0, 0, 0, 0])

### Vector addition and substruction

In [45]:
x=np.array([1,2])
y=np.array([3,4])


In [46]:
z=x+y
z

array([4, 6])

In [47]:
p=3*x
p

array([3, 6])

In [48]:
#dot product
np.dot(x,y)

11

## 2d Matrix operations

In [49]:
m=np.array([[1,2],[3,4]])
n=np.array([[10,20],[30,40]])
print(m,'\n\n',n)

[[1 2]
 [3 4]] 

 [[10 20]
 [30 40]]


In [50]:
#product elementwise
m*n

array([[ 10,  40],
       [ 90, 160]])

In [51]:
#matrix product
k=np.mat(m)*np.mat(n)
k

matrix([[ 70, 100],
        [150, 220]])

In [52]:
#Cross product
crp=np.cross(np.array([1,0,1]),np.array([1,-1,1]))
crp


array([ 1,  0, -1])

In [56]:
m

array([[1, 2],
       [3, 4]])

In [57]:
## Transpose of matrix
trans=np.transpose(m)
trans

array([[1, 3],
       [2, 4]])